@echo off
echo Stopping dev server...
taskkill /F /IM node.exe 2>nul

echo Cleaning cache...
npm cache clean --force

echo Removing node_modules...
if exist node_modules rmdir /s /q node_modules

echo Reinstalling dependencies...
npm install

echo Starting dev server...
npm run dev
